# Generated by Django 6.0.2 on 2026-02-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='RecipeIngredientQuantity',
        ),
    ]
